


export const colleges = [
{ title: ' A. T. Still University ' },
{ title: ' Abilene Christian University ' },
{ title: ' Abraham Baldwin Agricultural College ' },
{ title: ' Academy of Art University ' },
{ title: ' Adams State College ' },
{ title: ' Adelphi University ' },
{ title: ' Adrian College ' },
{ title: ' Agnes Scott College ' },
{ title: ' Air Force Institute of Technology ' },
{ title: ' Air University ' },
{ title: ' Alabama A&M University ' },
{ title: ' Alabama State University ' },
{ title: ' Alaska Bible College ' },
{ title: ' Alaska Pacific University ' },
{ title: ' Albertus Magnus College ' },
{ title: ' Albion College ' },
{ title: ' Albright College ' },
{ title: ' Alcorn State University ' },
{ title: ' Alderson-Broaddus College ' },
{ title: ' Alfred State College, State University of New York College of Technology ' },
{ title: ' Alfred University ' },
{ title: ' Allegheny College ' },
{ title: ' Allen College ' },
{ title: ' Allen University ' },
{ title: ' Alliant International University ' },
{ title: ' Allied University ' },
{ title: ' Alma College ' },
{ title: ' Alvernia College ' },
{ title: ' Alverno College ' },
{ title: ' Amberton University ' },
{ title: ' American Academy of Art ' },
{ title: ' American Bible College and Seminary ' },
{ title: ' American Coastline University ' },
{ title: ' The American College ' },
{ title: ' American Global University ' },
{ title: ' American Graduate School of International Management ' },
{ title: ' American Institute for Computer Sciences ' },
{ title: ' American InterContinental University ' },
{ title: ' American International College ' },
{ title: ' American Military University ' },
{ title: ' American Public University ' },
{ title: ' American University ' },
{ title: ' American University of Hawaii ' },
{ title: ' American University of Judasim ' },
{ title: ' Amherst College ' },
{ title: ' Anderson College ' },
{ title: ' Anderson University ' },
{ title: ' Andrew Jackson University ' },
{ title: ' Andrews University ' },
{ title: ' Angelo State University ' },
{ title: ' Anna Maria College ' },
{ title: ' Antioch College ' },
{ title: ' Antioch New England Graduate School ' },
{ title: ' Antioch University Los Angeles ' },
{ title: ' Antioch University Santa Barbara ' },
{ title: ' Antioch University Seattle ' },
{ title: ' Antioch University Yellow Springs OH ' },
{ title: ' Apache University ' },
{ title: ' Appalachian School of Law ' },
{ title: ' Appalachian State University ' },
{ title: ' Aquinas College ' },
{ title: ' Arcadia University ' },
{ title: ' Argosy University ' },
{ title: ' Arizona International College ' },
{ title: ' Arizona State University ' },
{ title: ' Arizona State University West ' },
{ title: ' Arkansas State University ' },
{ title: ' Arkansas Tech University ' },
{ title: ' Arlington Baptist College ' },
{ title: ' Armstrong Atlantic State University ' },
{ title: ' Art Center College of Design ' },
{ title: ' Art Institute of Chicago ' },
{ title: ' Art Institute of Ft Lauderdale ' },
{ title: ' The Art Institute of Phoenix ' },
{ title: ' The Art Institute of Southern California ' },
{ title: ' The Art Institute of Washington ' },
{ title: ' Asbury College ' },
{ title: ' Ashford University ' },
{ title: ' Ashland University ' },
{ title: ' Aspen University ' },
{ title: ' Assumption College ' },
{ title: ' Athena University ' },
{ title: ' Athens State College ' },
{ title: ' Atlantic Union College ' },
{ title: ' Auburn University ' },
{ title: ' Auburn University, Montgomery ' },
{ title: ' Augsburg College ' },
{ title: ' Augusta State University ' },
{ title: ' Augustana College, Rock Island Illinois ' },
{ title: ' Augustana College, Sioux Falls South Dakota ' },
{ title: ' Aurora University ' },
{ title: ' Austin College ' },
{ title: ' Austin Peay State University ' },
{ title: ' Averett College ' },
{ title: ' Avila College ' },
{ title: ' Azusa Pacific University ' },
{ title: ' Babson College ' },
{ title: ' Bacone College ' },
{ title: ' Baker College ' },
{ title: ' Baker University ' },
{ title: ' Baldwin-Wallace College ' },
{ title: ' Ball State University ' },
{ title: ' Baltimore Hebrew University ' },
{ title: ' Bank Street College of Education ' },
{ title: ' Baptist Bible College and Seminary ' },
{ title: ' The Baptist College of Florida ' },
{ title: ' Barber-Scotia College ' },
{ title: ' Bard College ' },
{ title: ' Barclay College ' },
{ title: ' Barnard College ' },
{ title: ' Barrington University ' },
{ title: ' Barry University ' },
{ title: ' Barton College ' },
{ title: ' Bastyr University ' },
{ title: ' Bates College ' },
{ title: ' Bay Path College ' },
{ title: ' Baylor College of Dentistry ' },
{ title: ' Baylor College of Medicine ' },
{ title: ' Baylor University ' },
{ title: ' Belhaven College ' },
{ title: ' Bellarmine University ' },
{ title: ' Bellevue University ' },
{ title: ' Belmont Abbey College ' },
{ title: ' Belmont University ' },
{ title: ' Beloit College ' },
{ title: ' Bemidji State University ' },
{ title: ' Benedict College ' },
{ title: ' Benedictine College ' },
{ title: ' Benedictine University ' },
{ title: ' Bennett College ' },
{ title: ' Bennington College ' },
{ title: ' Bentley College ' },
{ title: ' Berea College ' },
{ title: ' Berkeley College ' },
{ title: ' Berklee College of Music ' },
{ title: ' Berry College ' },
{ title: ' Bethany Bible College ' },
{ title: ' Bethany College, West Virginia ' },
{ title: ' Bethany College, Lindsborg, KS ' },
{ title: ' Bethany College, Scotts Valley, CA ' },
{ title: ' Bethany Lutheran College ' },
{ title: ' Bethel College and Seminary, Saint Paul Minnesota ' },
{ title: ' Bethel College, McKenzie, Tennessee ' },
{ title: ' Bethel College, Mishawaka, Indiana ' },
{ title: ' Bethel College, Newton, Kansas ' },
{ title: ' Bethune-Cookman College ' },
{ title: ' Bienville University ' },
{ title: ' Biola University ' },
{ title: ' Birmingham-Southern College ' },
{ title: ' Bismarck State College ' },
{ title: ' Black Hills State University ' },
{ title: ' Blackburn College ' },
{ title: ' Bloomfield College ' },
{ title: ' Bloomsburg University ' },
{ title: ' Blue Mountain College ' },
{ title: ' Bluefield College ' },
{ title: ' Bluefield State College ' },
{ title: ' Bluffton University ' },
{ title: ' Bob Jones University ' },
{ title: ' Boise State University ' },
{ title: ' The Boston Architectural Center ' },
{ title: ' Boston College ' },
{ title: ' Boston Conservatory ' },
{ title: ' Boston University ' },
{ title: ' Bowdoin College ' },
{ title: ' Bowie State University ' },
{ title: ' Bowling Green State University ' },
{ title: ' Bradford College ' },
{ title: ' Bradley University ' },
{ title: ' Brandeis University ' },
{ title: ' Brenau University ' },
{ title: ' Brevard College ' },
{ title: ' Brewton-Parker College ' },
{ title: ' Briar Cliff University ' },
{ title: ' Bridgewater College ' },
{ title: ' Bridgewater State College ' },
{ title: ' Brigham Young University ' },
{ title: ' Brigham Young University Hawaii ' },
{ title: ' Brigham Young University Idaho ' },
{ title: ' Brooklyn College ' },
{ title: ' Brooklyn Law School ' },
{ title: ' Brooks Institute ' },
{ title: ' Brown University ' },
{ title: ' Bryan College ' },
{ title: ' Bryant College ' },
{ title: ' Bryn Mawr College ' },
{ title: ' Bucknell University ' },
{ title: ' Buena Vista University ' },
{ title: ' Butler University ' },
{ title: ' C. R. Drew University of Medicine and Science ' },
{ title: ' Cabarrus College of Health Sciences ' },
{ title: ' Cabrini College ' },
{ title: ' Caldwell College ' },
{ title: ' California Baptist University ' },
{ title: ' California Coast University ' },
{ title: ' California College of the Arts ' },
{ title: ' California College for Health Sciences ' },
{ title: ' California College of Podiatric Medicine ' },
{ title: ' California Institute of the Arts ' },
{ title: ' California Institute for Human Science ' },
{ title: ' California Institute of Integral Studies ' },
{ title: ' California Institute of Technology ' },
{ title: ' California Lutheran University ' },
{ title: ' The California Maritime Academy ' },
{ title: ' California National University for Advanced Studies ' },
{ title: ' California Pacific University ' },
{ title: ' California Polytechnic State University, San Luis Obispo ' },
{ title: ' California State Polytechnic University, Pomona ' },
{ title: ' California State University, Bakersfield ' },
{ title: ' California State University, Channel Islands ' },
{ title: ' California State University, Chico ' },
{ title: ' California State University, Dominguez Hills ' },
{ title: ' California State University, Fresno ' },
{ title: ' California State University, Fullerton ' },
{ title: ' California State University, Hayward ' },
{ title: ' California State University, Long Beach ' },
{ title: ' California State University, Los Angeles ' },
{ title: ' California State University, Monterey ' },
{ title: ' California State University, Northridge ' },
{ title: ' California State University, Sacramento ' },
{ title: ' California State University, San Bernardino ' },
{ title: ' California State University, San Marcos ' },
{ title: ' California State University, Stanislaus ' },
{ title: ' California University of Pennsylvania ' },
{ title: ' Calumet College of St. Joseph ' },
{ title: ' Calvin College ' },
{ title: ' Cambridge College ' },
{ title: ' Cameron University ' },
{ title: ' Campbell University ' },
{ title: ' Campbellsville University ' },
{ title: ' Canisius College ' },
{ title: ' Canyon College ' },
{ title: ' Capella University ' },
{ title: ' Capital University ' },
{ title: ' Capitol College ' },
{ title: ' Cardinal Stritch University ' },
{ title: ' Carleton College ' },
{ title: ' Carlos Albizu University ' },
{ title: ' Carlow College ' },
{ title: ' Carnegie Institution of Washington ' },
{ title: ' Carnegie Mellon University ' },
{ title: ' Carrol University ' },
{ title: ' Carroll College, Helena, MT ' },
{ title: ' Carson-Newman College ' },
{ title: ' Carthage College ' },
{ title: ' Case Western Reserve University ' },
{ title: ' Castleton State College ' },
{ title: ' Catawba College ' },
{ title: ' The Catholic University of America ' },
{ title: ' Cazenovia College ' },
{ title: ' Cedar Crest College ' },
{ title: ' Cedarville University ' },
{ title: ' Centenary College of Louisiana ' },
{ title: ' Centenary College of New Jersey ' },
{ title: ' Center for Creative Studies College of Art and Design ' },
{ title: ' Central Bible College ' },
{ title: ' Central Christian College of the Bible ' },
{ title: ' Central Christian College of Kansas ' },
{ title: ' Central College ' },
{ title: ' Central Connecticut State University ' },
{ title: ' Central Methodist College ' },
{ title: ' Central Michigan University ' },
{ title: ' Central Missouri State University ' },
{ title: ' Central Pennsylvania College ' },
{ title: ' Central State University ' },
{ title: ' Central Washington University ' },
{ title: ' Centre College, Danville Kentucky ' },
{ title: ' Century University ' },
{ title: ' Chadron State College ' },
{ title: ' Chadwick University ' },
{ title: ' Chaminade University of Honolulu, Hawaii ' },
{ title: ' Champlain College ' },
{ title: ' Chapman University ' },
{ title: ' Charles R. Drew University of Medicine and Science ' },
{ title: ' Charleston Southern ' },
{ title: ' Charter Oak State College ' },
{ title: ' Chatham College ' },
{ title: ' Cheyney University of Pennsylvania ' },
{ title: ' Chicago-Kent College of Law ' },
{ title: ' Chicago School of Professional Psychology ' },
{ title: ' Chicago State University ' },
{ title: ' Chowan College ' },
{ title: ' Christendom College ' },
{ title: ' Christian Bible College and Seminary ' },
{ title: ' Christian Brothers University ' },
{ title: ' Christopher Newport University ' },
{ title: ' Circleville Bible College ' },
{ title: ' The Citadel ' },
{ title: ' City Colleges of Chicago ' },
{ title: ' City University, Bellevue Washington ' },
{ title: ' City University of Los Angeles ' },
{ title: ' City University of New York ' },
{ title: ' Claflin College ' },
{ title: ' Claremont Graduate University ' },
{ title: ' Claremont McKenna College ' },
{ title: ' Clarion University ' },
{ title: ' Clark Atlanta University ' },
{ title: ' Clark College ' },
{ title: ' Clark University ' },
{ title: ' Clarke College ' },
{ title: ' Clarkson University ' },
{ title: ' Clayton College and State University ' },
{ title: ' Clayton College of Natural Health ' },
{ title: ' Clemson University ' },
{ title: ' Clear Creek Baptist Bible College ' },
{ title: ' Clearwater Christian College ' },
{ title: ' Cleary University ' },
{ title: ' Cleveland Chiropractic College ' },
{ title: ' Cleveland Institute of Art ' },
{ title: ' Cleveland Institute of Music ' },
{ title: ' Cleveland State University ' },
{ title: ' Clinch Valley College ' },
{ title: ' Coastal Carolina University ' },
{ title: ' Coe College ' },
{ title: ' Cogswell Polytechnical College ' },
{ title: ' Coker College ' },
{ title: ' Colby College ' },
{ title: ' Colby-Sawyer College ' },
{ title: ' Colgate University ' },
{ title: ' Coleman College ' },
{ title: ' College of the Atlantic ' },
{ title: ' College of Charleston ' },
{ title: ' College of Eastern Utah ' },
{ title: ' College of the Holy Cross ' },
{ title: ' College of Idaho ' },
{ title: ' The College of Insurance ' },
{ title: ' The College of Metaphysical Studies ' },
{ title: ' College Misericordia ' },
{ title: ' College of Mount Saint Joseph ' },
{ title: ' College of Mount Saint Vincent ' },
{ title: ' The College of New Jersey ' },
{ title: ' College of New Rochelle ' },
{ title: ' College of Notre Dame of Maryland ' },
{ title: ' College of the Ozarks ' },
{ title: ' College of Saint Benedict ' },
{ title: ' College of Saint Catherine ' },
{ title: ' College of Saint Elizabeth ' },
{ title: ' College of Saint Joseph ' },
{ title: ' College of Saint Mary ' },
{ title: ' College of Saint Scholastica ' },
{ title: ' The College of Saint Thomas More ' },
{ title: ' The College of Saint Rose ' },
{ title: ' The College of Santa Fe ' },
{ title: ' College of William and Mary ' },
{ title: ' The College of Wooster ' },
{ title: ' Colorado Christian University ' },
{ title: ' Colorado College ' },
{ title: ' Colorado School of Mines ' },
{ title: ' Colorado State University ' },
{ title: ' Colorado State - Pueblo ' },
{ title: ' Colorado Technical University ' },
{ title: ' Columbia College ' },
{ title: ' Columbia College, South Carolina ' },
{ title: ' Columbia College of Missouri ' },
{ title: ' Columbia International University ' },
{ title: ' Columbia Southern University ' },
{ title: ' Columbia Union College ' },
{ title: ' Columbia University ' },
{ title: ' Columbus College of Art and Design ' },
{ title: ' Columbus State University ' },
{ title: ' Concord College ' },
{ title: ' Concordia College, Ann Arbor Michigan ' },
{ title: ' Concordia College, Austin Texas ' },
{ title: ' Concordia College, Bronxville, New York ' },
{ title: ' Concordia College, Moorhead Minnesota ' },
{ title: ' Concordia College, Saint Paul Minnesota ' },
{ title: ' Concordia College, Selma Alabama ' },
{ title: ' Concordia College, Seward Nebraska ' },
{ title: ' Concordia University, Irvine California ' },
{ title: ' Concordia University, Mequon Wisconsin ' },
{ title: ' Concordia University, Portland Oregon ' },
{ title: ' Concordia University, Chicago ' },
{ title: ' Connecticut College ' },
{ title: ' Converse College ' },
{ title: ' Conway School of Landscape Design ' },
{ title: ' Cooper Union for the Advancement of Science and Art ' },
{ title: ' Coppin State College ' },
{ title: ' Cornell College, Iowa ' },
{ title: ' Corcoran College of Art + Design ' },
{ title: ' Cornell University ' },
{ title: ' Cornerstone University ' },
{ title: ' Cornish College of the Arts ' },
{ title: ' Cottey College ' },
{ title: ' Covenant College ' },
{ title: ' Creighton University ' },
{ title: ' Crichton College ' },
{ title: ' Crossroads College ' },
{ title: ' Crown College ' },
{ title: ' Culver-Stockton College ' },
{ title: ' Cumberland College ' },
{ title: ' Cumberland University ' },
{ title: ' Curry College ' },
{ title: ' Cypress College ' },
{ title: ' Daemen College ' },
{ title: ' Dakota State University ' },
{ title: ' Dakota Wesleyan University ' },
{ title: ' Dallas Baptist University ' },
{ title: ' Dallas Theological Seminary ' },
{ title: ' Dana College ' },
{ title: ' Daniel Webster College ' },
{ title: ' Dartmouth College ' },
{ title: ' Davenport College ' },
{ title: ' Davidson College ' },
{ title: ' Davis and Elkins College ' },
{ title: ' Davis College ' },
{ title: ' Dawson College ' },
{ title: ' Dean College ' },
{ title: ' Deep Springs College ' },
{ title: ' Defiance College ' },
{ title: ' Delaware State University ' },
{ title: ' Delaware Valley College ' },
{ title: ' Delta College ' },
{ title: ' Delta State University ' },
{ title: ' Denison University ' },
{ title: ' Denver Seminary ' },
{ title: ' DePaul University ' },
{ title: ' DePauw University ' },
{ title: ' DeSales University ' },
{ title: ' DeVry University ' },
{ title: ' DeVry University, Columbus ' },
{ title: ' Diablo Valley College ' },
{ title: ' Dickinson College ' },
{ title: ' Dickinson State University ' },
{ title: ' Digital Media Arts College ' },
{ title: ' Dillard University ' },
{ title: ' Dixie State College ' },
{ title: ' Doane College ' },
{ title: ' Dominican College ' },
{ title: ' Dominican University ' },
{ title: ' Dominican University of California ' },
{ title: ' Dordt College ' },
{ title: ' Dowling College ' },
{ title: ' Drake University ' },
{ title: ' Drew University ' },
{ title: ' Drexel University ' },
{ title: ' Drury University ' },
{ title: ' Duke University ' },
{ title: ' Duquesne University ' },
{ title: ' D\'Youville College ' },
{ title: ' Earlham College ' },
{ title: ' East Carolina University ' },
{ title: ' East Central University, Ada Oklahoma ' },
{ title: ' East Stroudsburg State University ' },
{ title: ' East Tennessee State University ' },
{ title: ' East Texas Baptist University ' },
{ title: ' East-West University ' },
{ title: ' Eastern College ' },
{ title: ' Eastern Connecticut State University ' },
{ title: ' Eastern Illinois University ' },
{ title: ' Eastern Kentucky University ' },
{ title: ' Eastern Mennonite University ' },
{ title: ' Eastern Michigan University ' },
{ title: ' Eastern Nazarene College ' },
{ title: ' Eastern New Mexico University ' },
{ title: ' Eastern Oregon University ' },
{ title: ' Eastern Washington University ' },
{ title: ' Eckerd College ' },
{ title: ' Edgewood College ' },
{ title: ' Edinboro University of Pennsylvania ' },
{ title: ' Edward Waters College ' },
{ title: ' Elizabeth City State University ' },
{ title: ' Elizabethtown College ' },
{ title: ' Elmhurst College ' },
{ title: ' Elmira College ' },
{ title: ' Elms College ' },
{ title: ' Elon University ' },
{ title: ' Embry-Riddle Aeronautical University ' },
{ title: ' Emerson College ' },
{ title: ' Emmanuel College ' },
{ title: ' Emmaus Bible College ' },
{ title: ' Emory University ' },
{ title: ' Emory & Henry College ' },
{ title: ' Empire State College ' },
{ title: ' Emporia State University ' },
{ title: ' Endicott College ' },
{ title: ' Erskine College ' },
{ title: ' Eureka College ' },
{ title: ' Evangel University ' },
{ title: ' Everglades University ' },
{ title: ' Evergreen State College ' },
{ title: ' Excelsior College ' },
{ title: ' Fairfield University ' },
{ title: ' Fairleigh Dickinson University ' },
{ title: ' Fairmont State College ' },
{ title: ' Faith Baptist Bible College and Theological Seminary ' },
{ title: ' Faulkner University ' },
{ title: ' Fayetteville State University ' },
{ title: ' Felician College ' },
{ title: ' Ferris State University ' },
{ title: ' Ferrum College ' },
{ title: ' Fielding Graduate University ' },
{ title: ' Finch University of Health Sciences/The Chicago Medical School ' },
{ title: ' Finlandia University ' },
{ title: ' Fisk University ' },
{ title: ' Fitchburg State College ' },
{ title: ' Flagler College ' },
{ title: ' Florida A & M University ' },
{ title: ' Florida Atlantic University ' },
{ title: ' Florida Christian College ' },
{ title: ' Florida College ' },
{ title: ' Florida Gulf Coast University ' },
{ title: ' Florida Institute of Technology ' },
{ title: ' Florida International University ' },
{ title: ' Florida Memorial College ' },
{ title: ' Florida Metropolitan University ' },
{ title: ' Florida Southern College ' },
{ title: ' Florida State University ' },
{ title: ' Fontbonne University ' },
{ title: ' Fordham University ' },
{ title: ' Forest Institute of Professional Psychology ' },
{ title: ' Fort Hays State University ' },
{ title: ' Fort Lewis College ' },
{ title: ' Fort Valley State University ' },
{ title: ' Framingham State College ' },
{ title: ' Francis Marion University ' },
{ title: ' Franciscan University of Steubenville ' },
{ title: ' Franklin and Marshall College ' },
{ title: ' Franklin College ' },
{ title: ' Franklin Pierce University ' },
{ title: ' Franklin Pierce Law Center ' },
{ title: ' Franklin University ' },
{ title: ' Franklin W. Olin College of Engineering ' },
{ title: ' Freed-Hardeman University ' },
{ title: ' Freewill Baptist Bible College ' },
{ title: ' Fresno Pacific University ' },
{ title: ' Friends University ' },
{ title: ' Frostburg State University ' },
{ title: ' Full Sail University ' },
{ title: ' Fuller Theological Seminary ' },
{ title: ' Fullerton College ' },
{ title: ' Furman University ' },
{ title: ' Gallaudet University ' },
{ title: ' Gannon University ' },
{ title: ' Gardner-Webb University ' },
{ title: ' Geneva College ' },
{ title: ' George Fox University ' },
{ title: ' George Mason University ' },
{ title: ' George Washington University ' },
{ title: ' Georgetown College ' },
{ title: ' Georgetown University ' },
{ title: ' Georgian Court College ' },
{ title: ' Georgia College and State University ' },
{ title: ' Georgia Institute of Technology ' },
{ title: ' Georgia Perimeter College ' },
{ title: ' Georgia Southern University ' },
{ title: ' Georgia Southwestern State University ' },
{ title: ' Georgia State University ' },
{ title: ' Georgian Court College ' },
{ title: ' Gettysburg College ' },
{ title: ' Globe University ' },
{ title: ' Glenville State College ' },
{ title: ' Globe Institute of Technology ' },
{ title: ' Goddard College ' },
{ title: ' Golden Gate University ' },
{ title: ' Golden State Baptist College ' },
{ title: ' Goldey-Beacom College ' },
{ title: ' Gonzaga University ' },
{ title: ' Gooding Institute of Nurse Anesthesia ' },
{ title: ' Gordon College ' },
{ title: ' Gordon-Conwell Theological Seminary ' },
{ title: ' Goshen College ' },
{ title: ' Goucher College ' },
{ title: ' Governors State University ' },
{ title: ' Grace College ' },
{ title: ' Grace University ' },
{ title: ' Graceland University ' },
{ title: ' The Graduate Center, City University of New York ' },
{ title: ' Grambling State University ' },
{ title: ' Grand Canyon University ' },
{ title: ' Grand Valley State University ' },
{ title: ' Grand View College ' },
{ title: ' Granite State College ' },
{ title: ' Grantham University ' },
{ title: ' Great Lakes Maritime Academy ' },
{ title: ' Green Mountain College ' },
{ title: ' Greenleaf University ' },
{ title: ' Greensboro College ' },
{ title: ' Greenville College ' },
{ title: ' Greenwich University ' },
{ title: ' Grinnell College ' },
{ title: ' Grove City College ' },
{ title: ' Guilford College ' },
{ title: ' Gustavus Adolphus College, Saint Peter, Minnesota ' },
{ title: ' Gutenberg College ' },
{ title: ' Gwynedd-Mercy College ' },
{ title: ' Hamilton College ' },
{ title: ' Hamilton University ' },
{ title: ' Hamline University ' },
{ title: ' Hampden-Sydney College ' },
{ title: ' Hampshire College ' },
{ title: ' Hampton University ' },
{ title: ' Hannibal-LaGrange College ' },
{ title: ' Hanover College ' },
{ title: ' Hardin-Simmons University ' },
{ title: ' Harding University ' },
{ title: ' Harrington College of Design ' },
{ title: ' Harris-Stowe State College ' },
{ title: ' Hartwick College ' },
{ title: ' Harvard University ' },
{ title: ' Harvey Mudd College ' },
{ title: ' Haskell Indian Nations University ' },
{ title: ' Hastings College ' },
{ title: ' Haverford College ' },
{ title: ' Hawaii Pacific University ' },
{ title: ' Hebrew College ' },
{ title: ' Heidelberg College ' },
{ title: ' Henderson State Univerisity ' },
{ title: ' Hendrix College ' },
{ title: ' Henry Cogswell College ' },
{ title: ' Heritage University ' },
{ title: ' Hesser College ' },
{ title: ' Hesston College ' },
{ title: ' High Point University ' },
{ title: ' Hilbert College ' },
{ title: ' Hillsdale College ' },
{ title: ' Hillsdale Freewill Baptist College ' },
{ title: ' Hiram College ' },
{ title: ' Hobart and William Smith Colleges ' },
{ title: ' Hofstra University ' },
{ title: ' Hollins University ' },
{ title: ' Holy Cross College, Notre Dame Indiana ' },
{ title: ' Holy Family College ' },
{ title: ' Holy Names University ' },
{ title: ' Hood College ' },
{ title: ' Hope College ' },
{ title: ' Houghton College ' },
{ title: ' Houston Baptist University ' },
{ title: ' Howard Payne University ' },
{ title: ' Howard University ' },
{ title: ' Hult International Business School ' },
{ title: ' Humboldt State University ' },
{ title: ' Hunter College ' },
{ title: ' Huntingdon College ' },
{ title: ' Huntington University ' },
{ title: ' Huron University ' },
{ title: ' Husson College ' },
{ title: ' Huston-Tillotson College ' },
{ title: ' Idaho State University ' },
{ title: ' Illinois College ' },
{ title: ' Illinois Institute of Technology ' },
{ title: ' Illinois State University ' },
{ title: ' Illinois Wesleyan University ' },
{ title: ' Immaculata College ' },
{ title: ' Indiana Institute of Technology ' },
{ title: ' Indiana State University ' },
{ title: ' Indiana Wesleyan University ' },
{ title: ' Indiana University ' },
{ title: ' Indiana University Northwest ' },
{ title: ' Indiana University of Pennsylvania ' },
{ title: ' Indiana University at South Bend ' },
{ title: ' Indiana University Southeast ' },
{ title: ' Indiana University - Purdue University, Columbus ' },
{ title: ' Indiana University - Purdue University, Fort Wayne ' },
{ title: ' Indiana University - Purdue University, Indianapolis ' },
{ title: ' Institute for Christian Works ' },
{ title: ' Institute of Computer Technology ' },
{ title: ' Institute of Paper Science and Technology ' },
{ title: ' Institute for Transpersonal Psychology ' },
{ title: ' Inter American University of Puerto Rico ' },
{ title: ' International College ' },
{ title: ' International Fine Arts College ' },
{ title: ' International Institue of the Americas ' },
{ title: ' International Reform University ' },
{ title: ' Iona College ' },
{ title: ' Iowa State University ' },
{ title: ' Iowa Wesleyan College ' },
{ title: ' Irvine University College of Law ' },
{ title: ' Ithaca College ' },
{ title: ' Jackson State University ' },
{ title: ' Jacksonville State University ' },
{ title: ' Jacksonville University ' },
{ title: ' James Madison University ' },
{ title: ' Jamestown College ' },
{ title: ' Jarvis Christian College ' },
{ title: ' Jewish Theological Seminary ' },
{ title: ' John Brown University ' },
{ title: ' John Carroll University ' },
{ title: ' John F. Kennedy University ' },
{ title: ' John Jay College of Criminal Justice ' },
{ title: ' The Johns Hopkins University ' },
{ title: ' Johnson and Wales University ' },
{ title: ' Johnson Bible College ' },
{ title: ' Johnson C. Smith University ' },
{ title: ' Johnson State College ' },
{ title: ' Joint Military Intelligence College ' },
{ title: ' Jones College ' },
{ title: ' Jones International University ' },
{ title: ' Judson College, Marion AL ' },
{ title: ' Judson College, Elgin IL ' },
{ title: ' The Julliard School ' },
{ title: ' Juniata College ' },
{ title: ' Kalamazoo College ' },
{ title: ' Kansas City Art Institute ' },
{ title: ' Kansas Newman College ' },
{ title: ' Kansas State University ' },
{ title: ' Kansas Wesleyan University ' },
{ title: ' Kaplan University ' },
{ title: ' Kean University ' },
{ title: ' Keck Graduate Institute ' },
{ title: ' Keene State College ' },
{ title: ' Keiser University ' },
{ title: ' Kendall College ' },
{ title: ' Kennedy-Western University ' },
{ title: ' Kennesaw State University ' },
{ title: ' Kent State University ' },
{ title: ' Kentucky Christian College ' },
{ title: ' Kentucky State University ' },
{ title: ' Kentucky Wesleyan College ' },
{ title: ' Kenyon College ' },
{ title: ' Kettering University ' },
{ title: ' Keuka College ' },
{ title: ' King College ' },
{ title: ' King\'s College, Wilkes-Barre, PA ' },
{ title: ' The King\'s College, New York City, NY ' },
{ title: ' Knox College ' },
{ title: ' Knox Theological Seminary ' },
{ title: ' Knoxville College ' },
{ title: ' Kutztown University of Pennsylvania ' },
{ title: ' La Roche College ' },
{ title: ' La Salle University ' },
{ title: ' La Sierra University ' },
{ title: ' Lafayette College ' },
{ title: ' LaGrange College ' },
{ title: ' Lake Erie College ' },
{ title: ' Lake Forest College ' },
{ title: ' Lake Forest Graduate School of Management ' },
{ title: ' Lake Superior State University ' },
{ title: ' Lakeland College ' },
{ title: ' Lamar University ' },
{ title: ' Lambuth University ' },
{ title: ' Lancaster Bible College ' },
{ title: ' Lancaster Theological Seminary ' },
{ title: ' Lander University ' },
{ title: ' Landmark College ' },
{ title: ' Langston University ' },
{ title: ' Lane College ' },
{ title: ' Lasell College ' },
{ title: ' Lawrence Technological University ' },
{ title: ' Lawrence University ' },
{ title: ' Le Moyne College ' },
{ title: ' Lebanon Valley College ' },
{ title: ' Lee College ' },
{ title: ' Lee University ' },
{ title: ' Lees-McRae College ' },
{ title: ' Lehigh Univervsity ' },
{ title: ' Le Moyne College ' },
{ title: ' LeMoyne-Owen College ' },
{ title: ' Lenoir-Rhyne College ' },
{ title: ' Lenox Institute of Water Technology ' },
{ title: ' Lesley University ' },
{ title: ' LeTourneau University ' },
{ title: ' Lewis & Clark College ' },
{ title: ' Lewis-Clark State College ' },
{ title: ' Lewis University ' },
{ title: ' Liberty University ' },
{ title: ' Life Pacific College ' },
{ title: ' Life University ' },
{ title: ' Limestone College ' },
{ title: ' Lincoln Christian College and Seminary ' },
{ title: ' Lincoln College ' },
{ title: ' Lincoln Memorial University ' },
{ title: ' Lincoln University, Jefferson City Missouri ' },
{ title: ' Lincoln University, San Francisco California ' },
{ title: ' Lincoln University of Pennsylvania ' },
{ title: ' Lindenwood College ' },
{ title: ' Lindsey Wilson College ' },
{ title: ' Linfield College ' },
{ title: ' Lipscomb University ' },
{ title: ' Lock Haven University ' },
{ title: ' Logan College of Chiropractic ' },
{ title: ' Loma Linda University ' },
{ title: ' Long Island University ' },
{ title: ' Longwood College ' },
{ title: ' Loras College ' },
{ title: ' Louisburg College ' },
{ title: ' Louisiana Baptist Universty ' },
{ title: ' Louisiana College ' },
{ title: ' Louisiana State University at Alexandria ' },
{ title: ' Louisiana State University at Baton Rouge ' },
{ title: ' Louisiana State University Health Sciences Center New Orleans ' },
{ title: ' Louisiana State University at Shreveport ' },
{ title: ' Louisiana Tech University ' },
{ title: ' Lourdes College ' },
{ title: ' Loyola College, Baltimore ' },
{ title: ' Loyola Marymount University ' },
{ title: ' Loyola University, Chicago ' },
{ title: ' Loyola University, New Orleans ' },
{ title: ' Lubbock Christian University ' },
{ title: ' Luther College ' },
{ title: ' Luther Seminary ' },
{ title: ' Lutheran Bible Institute ' },
{ title: ' Lutheran Theological Seminary at Gettysburg ' },
{ title: ' Lycoming College ' },
{ title: ' Lyme Academy of Fine Arts ' },
{ title: ' Lynchburg College ' },
{ title: ' Lyndon State College ' },
{ title: ' Lynn University ' },
{ title: ' Lyon College ' },
{ title: ' Macalester College ' },
{ title: ' MacMurray College ' },
{ title: ' Madonna University ' },
{ title: ' Magdalen College ' },
{ title: ' Maharishi University of Management ' },
{ title: ' Maine College of Art ' },
{ title: ' Maine Maritime Academy ' },
{ title: ' Malone College ' },
{ title: ' Manchester College ' },
{ title: ' Manhattan College ' },
{ title: ' Manhattanville College ' },
{ title: ' Mansfield University ' },
{ title: ' Maranatha Baptist Bible College ' },
{ title: ' Marian College ' },
{ title: ' Marietta College ' },
{ title: ' Marlboro College ' },
{ title: ' Marlboro College Graduate Center ' },
{ title: ' Marist College ' },
{ title: ' Marquette University ' },
{ title: ' Mars Hill College ' },
{ title: ' Marshall University ' },
{ title: ' Mary Baldwin College ' },
{ title: ' Marygrove College ' },
{ title: ' Maryland Institute, College of Art ' },
{ title: ' Marylhurst University ' },
{ title: ' Marymount College ' },
{ title: ' Marymount Manhattan College ' },
{ title: ' Marymount University ' },
{ title: ' Maryville College ' },
{ title: ' Maryville University of Saint Louis ' },
{ title: ' Marywood University ' },
{ title: ' Massachusetts College of Art ' },
{ title: ' Massachusetts College of Liberal Arts ' },
{ title: ' Massachusetts College of Pharmacy and Health Sciences ' },
{ title: ' Massachusetts Institute of Technology ' },
{ title: ' Massachusetts Maritime Academy ' },
{ title: ' Massachusetts School of Professional Psychology ' },
{ title: ' The Master\'s College ' },
{ title: ' The Mayo Foundation ' },
{ title: ' Mayville State University ' },
{ title: ' McDaniel College ' },
{ title: ' The McGregor School of Antioch University ' },
{ title: ' McKendree College ' },
{ title: ' McMurry University ' },
{ title: ' McNeese State University ' },
{ title: ' MCP Hahnemann University ' },
{ title: ' McPherson College ' },
{ title: ' Medaille College ' },
{ title: ' Medical College of Georgia ' },
{ title: ' Medical College of Ohio ' },
{ title: ' Medical College of Pennsylvania and Hahnemann University ' },
{ title: ' Medical College of Wisconsin ' },
{ title: ' Medical University of South Carolina ' },
{ title: ' Meharry Medical College ' },
{ title: ' Menlo College ' },
{ title: ' Mercer University ' },
{ title: ' Mercy College ' },
{ title: ' Mercy College of Health Sciences ' },
{ title: ' Mercyhurst College ' },
{ title: ' Meredith College ' },
{ title: ' Merrimack College ' },
{ title: ' Mesa State College ' },
{ title: ' Messiah College ' },
{ title: ' Methodist College ' },
{ title: ' Methodist Theological School in Ohio ' },
{ title: ' Metropolitan College ' },
{ title: ' Metropolitan College of New York ' },
{ title: ' Metropolitan State College of Denver ' },
{ title: ' Metropolitan State University ' },
{ title: ' Miami Christian University ' },
{ title: ' Miami University of Ohio ' },
{ title: ' Michigan Jewish Institute ' },
{ title: ' Michigan State University ' },
{ title: ' Michigan Technological University ' },
{ title: ' Mid-America Nazarene University ' },
{ title: ' Middle Georgia College ' },
{ title: ' Middle Tennessee State University ' },
{ title: ' Middlebury College ' },
{ title: ' Midwestern Baptist College ' },
{ title: ' Midwestern State University ' },
{ title: ' Miles College ' },
{ title: ' Millersville University ' },
{ title: ' Milligan College ' },
{ title: ' Millikin University ' },
{ title: ' Mills College ' },
{ title: ' Millsaps College ' },
{ title: ' Milwaukee School of Engineering ' },
{ title: ' Minneapolis College of Art and Design ' },
{ title: ' Minnesota State University Mankato ' },
{ title: ' Minnesota State University Moorhead ' },
{ title: ' Minot State University ' },
{ title: ' Minot State University--Bottineau ' },
{ title: ' Mississippi College ' },
{ title: ' Mississippi State University ' },
{ title: ' Mississippi University for Women ' },
{ title: ' Mississippi Valley State University ' },
{ title: ' Missouri Baptist College ' },
{ title: ' Missouri Southern State College ' },
{ title: ' Missouri State University ' },
{ title: ' Missouri Tech ' },
{ title: ' Missouri University of Science and Technology ' },
{ title: ' Missouri Valley College ' },
{ title: ' Missouri Western State College ' },
{ title: ' Mitchell College ' },
{ title: ' Molloy College ' },
{ title: ' Monmouth College, Monmouth Illinois ' },
{ title: ' Monmouth University, West Long Branch New Jersey ' },
{ title: ' Monroe College ' },
{ title: ' Montana State University-Billings ' },
{ title: ' Montana State University-Bozeman ' },
{ title: ' Montana State University College of Technology, Great Falls ' },
{ title: ' Montana State University-Northern Havre ' },
{ title: ' Montana Tech ' },
{ title: ' Montclair State University ' },
{ title: ' Monterey College of Law ' },
{ title: ' Monterey Institute of International Studies ' },
{ title: ' Montreat College ' },
{ title: ' Moravian College ' },
{ title: ' Morehead State University ' },
{ title: ' Morehouse College ' },
{ title: ' Morehouse School of Medicine ' },
{ title: ' Morgan State University ' },
{ title: ' Morningside College ' },
{ title: ' Morris Brown College ' },
{ title: ' Morris College ' },
{ title: ' Mount Aloysius College ' },
{ title: ' Mount Holyoke College ' },
{ title: ' Mount Ida College ' },
{ title: ' Mount Marty College ' },
{ title: ' Mount Mary College ' },
{ title: ' Mount Mercy College ' },
{ title: ' Mount Olive College ' },
{ title: ' Mount Saint Mary College ' },
{ title: ' Mount St. Mary\'s College and Seminary, Emmitsburg Maryland ' },
{ title: ' Mount St. Mary\'s College, Los Angeles California ' },
{ title: ' Mount Senario College ' },
{ title: ' Mt. Sierra College ' },
{ title: ' Mount Union College ' },
{ title: ' Mount Vernon Nazarene College ' },
{ title: ' Mountain State University ' },
{ title: ' Muhlenberg College ' },
{ title: ' Murray State University ' },
{ title: ' Muskingum College ' },
{ title: ' Naropa University ' },
{ title: ' National American University ' },
{ title: ' National Defense University ' },
{ title: ' The National Graduate School ' },
{ title: ' National-Louis University ' },
{ title: ' National Technological University ' },
{ title: ' National University ' },
{ title: ' National University of Health Sciences ' },
{ title: ' The Naval Postgraduate School ' },
{ title: ' Nazarene Bible College ' },
{ title: ' Nazareth College ' },
{ title: ' Nebraska Methodist College ' },
{ title: ' Nebraska Wesleyan University ' },
{ title: ' Neumann College ' },
{ title: ' Nevada State College ' },
{ title: ' New Brunswick Theological Seminary ' },
{ title: ' New College of Florida ' },
{ title: ' New England College ' },
{ title: ' New England College of Optometry ' },
{ title: ' New England Conservatory of Music ' },
{ title: ' New England Institute of Technology ' },
{ title: ' New England Law ' },
{ title: ' New England School of Communications ' },
{ title: ' New Jersey City University ' },
{ title: ' New Jersey Institute of Technology ' },
{ title: ' New Mexico Highlands University ' },
{ title: ' New Mexico Institute of Mining and Technology ' },
{ title: ' New Mexico State University ' },
{ title: ' New Saint Andrews College ' },
{ title: ' New School of Architecture and Design ' },
{ title: ' New School University ' },
{ title: ' New World School of the Arts ' },
{ title: ' New York Academy of Art ' },
{ title: ' New York Institute of Technology ' },
{ title: ' New York Law School ' },
{ title: ' New York University ' },
{ title: ' Newberry College ' },
{ title: ' Newport University ' },
{ title: ' Niagara University ' },
{ title: ' Nicholls State University ' },
{ title: ' Nichols College ' },
{ title: ' Norfolk State University ' },
{ title: ' North Carolina Agricultural and Technical State University ' },
{ title: ' North Carolina Central University ' },
{ title: ' North Carolina School of the Arts ' },
{ title: ' North Carolina State University ' },
{ title: ' North Carolina Wesleyan College ' },
{ title: ' North Central College ' },
{ title: ' North Central University ' },
{ title: ' North Dakota State University--Fargo ' },
{ title: ' North Georgia College and State University, the Military College of Georgia ' },
{ title: ' North Greenville University ' },
{ title: ' North Park University ' },
{ title: ' Northcentral University ' },
{ title: ' Northeastern Illinois University ' },
{ title: ' Northeastern University ' },
{ title: ' Northeastern State University ' },
{ title: ' Northern Arizona University ' },
{ title: ' Northern Illinois University ' },
{ title: ' Northern Kentucky University ' },
{ title: ' Northern Michigan University ' },
{ title: ' Northern State University ' },
{ title: ' Northland College ' },
{ title: ' Northwest Christian College ' },
{ title: ' Northwest College of Art ' },
{ title: ' Northwest Missouri State University ' },
{ title: ' Northwest Nazarene University ' },
{ title: ' Northwest University ' },
{ title: ' Northwestern Oklahoma State University ' },
{ title: ' Northwestern State University, Louisiana ' },
{ title: ' Northwestern College, Iowa ' },
{ title: ' Northwestern College, Saint Paul, MN ' },
{ title: ' Northwestern Michigan College ' },
{ title: ' Northwestern University ' },
{ title: ' Northwood University ' },
{ title: ' Norwich University ' },
{ title: ' Notre Dame College of Ohio ' },
{ title: ' Notre Dame de Namur University ' },
{ title: ' Nova Southeastern University ' },
{ title: ' Nyack College ' },
{ title: ' Oakland University ' },
{ title: ' Oakwood College ' },
{ title: ' Oberlin College ' },
{ title: ' Occidental College ' },
{ title: ' Oglethorpe University ' },
{ title: ' Ohio Dominican University ' },
{ title: ' Ohio Northern University ' },
{ title: ' The Ohio State University ' },
{ title: ' Ohio University ' },
{ title: ' Ohio Valley College ' },
{ title: ' Ohio Wesleyan University ' },
{ title: ' Oklahoma Baptist University ' },
{ title: ' Oklahoma Christian University ' },
{ title: ' Oklahoma City University ' },
{ title: ' Oklahoma Panhandle State University ' },
{ title: ' Oklahoma State University ' },
{ title: ' Oklahoma State University Tulsa ' },
{ title: ' Oklahoma Wesleyan University ' },
{ title: ' Old Dominion University ' },
{ title: ' Olin College of Engineering ' },
{ title: ' Olivet College ' },
{ title: ' Olivet Nazarene University ' },
{ title: ' The Open University ' },
{ title: ' Oral Roberts University ' },
{ title: ' Oregon Graduate Institute of Science and Technology ' },
{ title: ' Oregon Health Sciences University ' },
{ title: ' Oregon Institute of Technology ' },
{ title: ' Oregon State University ' },
{ title: ' Otterbein College ' },
{ title: ' Ottawa University ' },
{ title: ' Ouachita Baptist University ' },
{ title: ' Our Lady of the Lake University ' },
{ title: ' Our Lady of Holy Cross College ' },
{ title: ' Pace University ' },
{ title: ' Pacific College of Oriental Medicine ' },
{ title: ' Pacific Lutheran University ' },
{ title: ' Pacific Northwest College of Art ' },
{ title: ' Pacific Oaks College ' },
{ title: ' Pacific States University ' },
{ title: ' Pacific Union College ' },
{ title: ' Pacific University ' },
{ title: ' Paine College ' },
{ title: ' Palm Beach Atlantic College ' },
{ title: ' Palmer College of Chiropractic ' },
{ title: ' Park College ' },
{ title: ' Parsons School of Design ' },
{ title: ' Patten College ' },
{ title: ' Patrick Henry College ' },
{ title: ' Paul Quinn College ' },
{ title: ' Paul Smith\'s College ' },
{ title: ' Peace College ' },
{ title: ' Pennsylvania College of Technology ' },
{ title: ' The Pennsylvania State University ' },
{ title: ' Pennsylvania State University at Altoona ' },
{ title: ' Pennsylvania State University, Great Valley ' },
{ title: ' Pennsylvania State University at Harrisburg ' },
{ title: ' Pennsylvania State University, Worthington Scranton ' },
{ title: ' Pensacola Christian College ' },
{ title: ' Pepperdine University ' },
{ title: ' Peru State College ' },
{ title: ' Pfeiffer University ' },
{ title: ' Pickering University ' },
{ title: ' Piedmont College ' },
{ title: ' Pikeville College ' },
{ title: ' Pine Manor College ' },
{ title: ' Pittsburg State University ' },
{ title: ' Pitzer College ' },
{ title: ' Philadelphia Biblical University ' },
{ title: ' Philadelphia University ' },
{ title: ' Philander Smith College ' },
{ title: ' Phillips University ' },
{ title: ' Plymouth State University, Plymouth New Hampshire ' },
{ title: ' Point Loma Nazarene College ' },
{ title: ' Point Park University ' },
{ title: ' Polytechnic University of New York ' },
{ title: ' Polytechnic University of Puerto Rico ' },
{ title: ' Pomona College ' },
{ title: ' Pontifical University ' },
{ title: ' Portland State University ' },
{ title: ' Potomac College ' },
{ title: ' Prairie View A & M University ' },
{ title: ' Pratt Institute ' },
{ title: ' Presbyterian College ' },
{ title: ' Prescott College ' },
{ title: ' Preston University ' },
{ title: ' Princeton University ' },
{ title: ' Principia College ' },
{ title: ' Providence College ' },
{ title: ' Purdue University ' },
{ title: ' Purdue University North Central ' },
{ title: ' Queens College ' },
{ title: ' Quincy University ' },
{ title: ' Quinnipiac College ' },
{ title: ' Radford University ' },
{ title: ' Ramapo College of New Jersey ' },
{ title: ' Randolph College ' },
{ title: ' Randolph-Macon College ' },
{ title: ' Rasmussen College ' },
{ title: ' Reed College ' },
{ title: ' Regent University ' },
{ title: ' Regis College ' },
{ title: ' Regis University ' },
{ title: ' Reinhardt College ' },
{ title: ' Remington College ' },
{ title: ' Rensselaer Polytechnic Institute ' },
{ title: ' Rhode Island College ' },
{ title: ' Rhode Island School of Design ' },
{ title: ' Rhodes College ' },
{ title: ' Rice University ' },
{ title: ' The Richard Stockton College of New Jersey ' },
{ title: ' Rider University ' },
{ title: ' Ringling School of Art and Design ' },
{ title: ' Ripon College ' },
{ title: ' Rivier College ' },
{ title: ' Roanoke College ' },
{ title: ' Robert Morris College, Illinois ' },
{ title: ' Robert Morris College, Pittsburgh, PA ' },
{ title: ' Roberts Wesleyan College ' },
{ title: ' Rochester Institute of Technology ' },
{ title: ' Rochester College ' },
{ title: ' The Rockefeller University ' },
{ title: ' Rockford College ' },
{ title: ' Rockhurst University ' },
{ title: ' Rocky Mountain College ' },
{ title: ' Roger Williams University ' },
{ title: ' Rogers State University ' },
{ title: ' Rollins College ' },
{ title: ' Roosevelt University ' },
{ title: ' Rose-Hulman Institute of Technology ' },
{ title: ' Rosemont College ' },
{ title: ' Rowan University ' },
{ title: ' Rush University ' },
{ title: ' Russell Sage College ' },
{ title: ' Rust College ' },
{ title: ' Rutgers University ' },
{ title: ' Rutgers University-Camden ' },
{ title: ' Rutgers University-Newark ' },
{ title: ' Ryokan College ' },
{ title: ' Sacred Heart University ' },
{ title: ' Sacred Heart University, Puerto Rico ' },
{ title: ' The Sage Colleges ' },
{ title: ' Saginaw Valley State University ' },
{ title: ' Saint Ambrose University ' },
{ title: ' Saint Andrews Presbyterian College ' },
{ title: ' Saint Anselm College ' },
{ title: ' Saint Anthony College of Nursing ' },
{ title: ' Saint Augustine\'s College ' },
{ title: ' Saint Bonaventure University ' },
{ title: ' Saint Cloud State University ' },
{ title: ' Saint Edwards University ' },
{ title: ' Saint Francis College, Brooklyn Heights, New York ' },
{ title: ' Saint Francis College, Fort Wayne, Indiana ' },
{ title: ' Saint Francis College, Loretto, Pennsylvania ' },
{ title: ' Saint Gregory\'s University ' },
{ title: ' Saint John Fisher College ' },
{ title: ' Saint John\'s College ' },
{ title: ' Saint John\'s University, Collegeville Minnesota ' },
{ title: ' Saint John\'s University, Jamaica New York ' },
{ title: ' Saint Joseph College ' },
{ title: ' Saint Joseph\'s College ' },
{ title: ' Saint Joseph\'s College of Maine ' },
{ title: ' Saint Joseph\'s University ' },
{ title: ' Saint Lawrence University ' },
{ title: ' Saint Leo University ' },
{ title: ' Saint Louis University ' },
{ title: ' Saint Louis Christian College ' },
{ title: ' Saint Martin\'s University ' },
{ title: ' Saint Mary-of-the-Woods College ' },
{ title: ' Saint Mary\'s College of California ' },
{ title: ' Saint Mary\'s College of Maryland ' },
{ title: ' Saint Mary\'s University of Minnesota ' },
{ title: ' Saint Mary\'s University of San Antonio ' },
{ title: ' Saint Meinrad\'s School of Theology ' },
{ title: ' Saint Michael\'s College ' },
{ title: ' Saint Norbert College ' },
{ title: ' Saint Olaf College ' },
{ title: ' Saint Paul\'s College ' },
{ title: ' Saint Peter\'s College ' },
{ title: ' Saint Petersburg College ' },
{ title: ' Saint Rose College ' },
{ title: ' Saint Thomas Aquinas College ' },
{ title: ' Saint Thomas University ' },
{ title: ' Saint Vincent College ' },
{ title: ' Saint Xavier University ' },
{ title: ' Salem College ' },
{ title: ' Salem International University ' },
{ title: ' Salem State College ' },
{ title: ' Salisbury State University ' },
{ title: ' The Salk Institute for Biological Studies ' },
{ title: ' Salve Regina University ' },
{ title: ' Sam Houston State University ' },
{ title: ' Samford University ' },
{ title: ' Samuel Merritt College ' },
{ title: ' San Diego State University ' },
{ title: ' San Francisco Art Institute ' },
{ title: ' San Francisco Law School ' },
{ title: ' San Francisco State University ' },
{ title: ' San Joaquin College of Law ' },
{ title: ' San Jose Christian College ' },
{ title: ' San Jose State University ' },
{ title: ' Santa Clara University ' },
{ title: ' Sarah Lawrence College ' },
{ title: ' Saratoga University School of Law ' },
{ title: ' Sarah Lawrence College ' },
{ title: ' Savannah College of Art and Design ' },
{ title: ' Savannah State University ' },
{ title: ' Saybrook Graduate School and Research Center ' },
{ title: ' Schiller International University ' },
{ title: ' School for International Training ' },
{ title: ' School of the Art Institute of Chicago ' },
{ title: ' School of Islamic and Social Sciences ' },
{ title: ' School of the Museum of Fine Arts, Boston ' },
{ title: ' School of the Visual Arts ' },
{ title: ' Schreiner College ' },
{ title: ' Scripps College ' },
{ title: ' The Scripps Research Institute ' },
{ title: ' Seattle Pacific University ' },
{ title: ' Seattle University ' },
{ title: ' Seton Hall University ' },
{ title: ' Seton Hill College ' },
{ title: ' Shasta Bible College ' },
{ title: ' Shawnee State University ' },
{ title: ' Shaw University ' },
{ title: ' Sheffield School of Interior Design ' },
{ title: ' Sheldon Jackson College ' },
{ title: ' Shenandoah University ' },
{ title: ' Shepherd College ' },
{ title: ' Sherman College of Straight Chiropractic ' },
{ title: ' Shimer College ' },
{ title: ' Shippensburg University of Pennsylvania ' },
{ title: ' Shorter College ' },
{ title: ' Siena College ' },
{ title: ' Siena Heights University ' },
{ title: ' Sierra Nevada College ' },
{ title: ' Silver Lake College ' },
{ title: ' Simmons College ' },
{ title: ' Simon\'s Rock College ' },
{ title: ' Simpson College, Redding California ' },
{ title: ' Simpson College, Indianola Iowa ' },
{ title: ' Skidmore College ' },
{ title: ' Slippery Rock University ' },
{ title: ' Smith Chapel Bible College ' },
{ title: ' Smith College ' },
{ title: ' Soka University of America ' },
{ title: ' Sonoma State University ' },
{ title: ' South Carolina State University ' },
{ title: ' South Dakota School of Mines and Technology  ' },
{ title: ' South Dakota State University ' },
{ title: ' South Pacific University ' },
{ title: ' South Texas College of Law ' },
{ title: ' Southampton College ' },
{ title: ' Southeast College of Technology ' },
{ title: ' Southeast Missouri State University ' },
{ title: ' Southeastern Bible College ' },
{ title: ' Southeastern College ' },
{ title: ' Southeastern Louisiana University ' },
{ title: ' Southeastern Oklahoma State University ' },
{ title: ' Southeastern University ' },
{ title: ' Southern Adventist University ' },
{ title: ' Southern Arkansas University ' },
{ title: ' Southern California University of Health Sciences ' },
{ title: ' Southern California University of Professional Studies ' },
{ title: ' Southern Connecticut State University ' },
{ title: ' Southern Illinois University at Carbondale ' },
{ title: ' Southern Illinois University at Edwardsville ' },
{ title: ' Southern Illinois University Medical School at Springsfield ' },
{ title: ' Southern Methodist University ' },
{ title: ' Southern Nazarene University ' },
{ title: ' Southern New Hampshire University ' },
{ title: ' Southern Oregon State College ' },
{ title: ' Southern Oregon University ' },
{ title: ' Southern Polytechnic State Univerisity ' },
{ title: ' Southern Vermont College ' },
{ title: ' Southern Virginia University ' },
{ title: ' Southern Wesleyan University ' },
{ title: ' Southern University, Baton Rouge ' },
{ title: ' Southern University, New Orleans ' },
{ title: ' Southern University, Shreveport-Bossier City ' },
{ title: ' Southern Utah University ' },
{ title: ' Southwest Baptist University ' },
{ title: ' Southwest Bible College and Seminary ' },
{ title: ' Southwest Florida College ' },
{ title: ' Southwest Minnesota State University ' },
{ title: ' Southwest University ' },
{ title: ' Southwestern Adventist University ' },
{ title: ' Southwestern Assemblies of God University ' },
{ title: ' Southwestern College, Kansas ' },
{ title: ' Southwestern College, New Mexico ' },
{ title: ' Southwestern Oklahoma State University ' },
{ title: ' Southwestern University ' },
{ title: ' Southwestern University School of Law ' },
{ title: ' Spalding University ' },
{ title: ' Spartanburg Methodist College ' },
{ title: ' Spelman College ' },
{ title: ' Spertus College ' },
{ title: ' Spring Arbor College ' },
{ title: ' Spring Hill College ' },
{ title: ' Springfield College ' },
{ title: ' Stamford International College ' },
{ title: ' Stanford University ' },
{ title: ' State University of New York at Albany ' },
{ title: ' State University of New York at Binghamton ' },
{ title: ' State University of New York at Buffalo ' },
{ title: ' State University of New York at Oswego ' },
{ title: ' State University of New York at Stony Brook ' },
{ title: ' State University of New York College of Agriculture and Technology, Cobleskill ' },
{ title: ' State University of New York College of Agriculture and Technology, Morrisville ' },
{ title: ' State University of New York College at Brockport ' },
{ title: ' State University of New York College at Buffalo (Buffalo State College) ' },
{ title: ' State University of New York College at Cortland ' },
{ title: ' State University of New York College of Environmental Science and Forestry ' },
{ title: ' State University of New York College at Farmingdale ' },
{ title: ' State University of New York College at Fredonia ' },
{ title: ' State University of New York College at Geneseo ' },
{ title: ' State University of New York College Maritime College at Fort Schuyler ' },
{ title: ' State University of New York College at New Paltz ' },
{ title: ' State University of New York College at Old Westbury ' },
{ title: ' State University of New York College at Oneonta ' },
{ title: ' State University of New York College at Oswego ' },
{ title: ' State University of New York College at Plattsburgh ' },
{ title: ' State University of New York College at Potsdam ' },
{ title: ' State University of New York College at Purchase ' },
{ title: ' State University of New York Institute of Technology at Canton ' },
{ title: ' State University of New York Institute of Technology at Delhi ' },
{ title: ' State University of New York Institute of Technology at Utica/Rome ' },
{ title: ' The Stefan University ' },
{ title: ' Stephen F. Austin State University ' },
{ title: ' Stephens College ' },
{ title: ' Sterling College, Sterling Kansas ' },
{ title: ' Sterling College, Kansas ' },
{ title: ' Sterling College, Vermont ' },
{ title: ' Stetson University ' },
{ title: ' Stevens-Henager College ' },
{ title: ' Stevens Institute of Technology ' },
{ title: ' Stevenson University ' },
{ title: ' Stillman College ' },
{ title: ' Stonehill College ' },
{ title: ' Stratford University ' },
{ title: ' Strayer University ' },
{ title: ' Suffolk University ' },
{ title: ' Sul Ross State University ' },
{ title: ' Summit University of Louisiana ' },
{ title: ' Susquehanna University ' },
{ title: ' Swarthmore College ' },
{ title: ' Sweet Briar College ' },
{ title: ' Syracuse University ' },
{ title: ' Tabor College ' },
{ title: ' Talladega College ' },
{ title: ' Tarleton State University ' },
{ title: ' Taylor University ' },
{ title: ' Teachers College ' },
{ title: ' Teikyo Marycrest University ' },
{ title: ' Teikyo Post University ' },
{ title: ' Temple University ' },
{ title: ' Tennessee State University ' },
{ title: ' Tennessee Technological University ' },
{ title: ' Tennessee Temple University ' },
{ title: ' Tennessee Wesleyan College ' },
{ title: ' Texas A&M International University ' },
{ title: ' Texas A&M University ' },
{ title: ' Texas A&M University, Commerce ' },
{ title: ' Texas A&M University, Corpus Christi ' },
{ title: ' Texas A&M University, Galveston ' },
{ title: ' Texas A&M University, Kingsville ' },
{ title: ' Texas A&M University, Texarkana ' },
{ title: ' Texas Chiropractic College ' },
{ title: ' Texas Christian University ' },
{ title: ' Texas Lutheran University ' },
{ title: ' Texas Southern University ' },
{ title: ' Texas State University ' },
{ title: ' Texas Tech University ' },
{ title: ' Texas Wesleyan University ' },
{ title: ' Texas Woman\'s University ' },
{ title: ' Thiel College ' },
{ title: ' Thomas Aquinas College, Santa Paula CA ' },
{ title: ' Thomas Edison State College ' },
{ title: ' Thomas College ' },
{ title: ' Thomas Cooley Law School ' },
{ title: ' Thomas More College ' },
{ title: ' Thomas Jefferson University ' },
{ title: ' Thunderbird School of Global Management ' },
{ title: ' Toccoa Falls College ' },
{ title: ' Tougaloo College ' },
{ title: ' Touro College ' },
{ title: ' Towson University ' },
{ title: ' The Transworld University ' },
{ title: ' Transylvania University ' },
{ title: ' Trevecca Nazarene University ' },
{ title: ' Trinity Baptist College ' },
{ title: ' Trinity Christian College ' },
{ title: ' Trinity College, Hartford Connecticut ' },
{ title: ' Trinity College of Florida ' },
{ title: ' Trinity College, Washington DC ' },
{ title: ' Trinity International University ' },
{ title: ' Trinity University ' },
{ title: ' Tri-State University ' },
{ title: ' Troy State University ' },
{ title: ' Troy State University - Dothan ' },
{ title: ' Truman State University ' },
{ title: ' Tufts University ' },
{ title: ' Tulane University ' },
{ title: ' Tusculum College ' },
{ title: ' Tuskegee University ' },
{ title: ' Uniformed Services Universty of the Health Sciences ' },
{ title: ' Union College, Barbourville KY ' },
{ title: ' Union College ' },
{ title: ' Union College ' },
{ title: ' Union Theological Seminary ' },
{ title: ' Union University ' },
{ title: ' The Union Institute ' },
{ title: ' United States Air Force Academy ' },
{ title: ' United States Coast Guard Academy ' },
{ title: ' United States Merchant Marine Academy ' },
{ title: ' United States Military Academy ' },
{ title: ' United States Naval Academy ' },
{ title: ' United States Open University ' },
{ title: ' United States Sports Academy ' },
{ title: ' United Theological Seminar ' },
{ title: ' Unity College ' },
{ title: ' University of Advancing Technology ' },
{ title: ' University of Akron ' },
{ title: ' University of Alabama ' },
{ title: ' University of Alabama, Birmingham ' },
{ title: ' University of Alabama, Huntsville ' },
{ title: ' University of Alaska, Anchorage ' },
{ title: ' University of Alaska, Fairbanks ' },
{ title: ' University of Alaska, Southeast ' },
{ title: ' University of Arizona ' },
{ title: ' University of Arkansas, Fayetteville ' },
{ title: ' University of Arkansas at Little Rock ' },
{ title: ' University of Arkansas at Monticello ' },
{ title: ' University of Arkansas at Pine Bluff ' },
{ title: ' University of the Arts ' },
{ title: ' University of Baltimore ' },
{ title: ' University of Bridgeport ' },
{ title: ' University of California, Berkeley ' },
{ title: ' University of California, Davis ' },
{ title: ' University of California, Hastings College of Law ' },
{ title: ' University of California, Irvine ' },
{ title: ' University of California, Los Angeles ' },
{ title: ' University of California, Merced ' },
{ title: ' University of California, Riverside ' },
{ title: ' University of California, San Diego ' },
{ title: ' University of California, San Francisco ' },
{ title: ' University of California, Santa Barbara ' },
{ title: ' University of California, Santa Cruz ' },
{ title: ' University of Central Arkansas ' },
{ title: ' University of Central Florida ' },
{ title: ' University of Central Oklahoma ' },
{ title: ' University of Charleston ' },
{ title: ' University of Chicago ' },
{ title: ' University of Cincinnati ' },
{ title: ' University of Colorado at Boulder ' },
{ title: ' University of Colorado, Colorado Springs ' },
{ title: ' University of Colorado, Denver ' },
{ title: ' University of Connecticut ' },
{ title: ' University of Dallas ' },
{ title: ' University of Dayton ' },
{ title: ' University of Delaware ' },
{ title: ' University of Denver ' },
{ title: ' University of Detroit Mercy ' },
{ title: ' University of the District of Columbia ' },
{ title: ' University of Dubuque ' },
{ title: ' University of Evansville ' },
{ title: ' University of Findlay ' },
{ title: ' University of Florida ' },
{ title: ' University of Georgia ' },
{ title: ' University of Great Falls ' },
{ title: ' University of Guam ' },
{ title: ' University of Hartford ' },
{ title: ' University of Hawai`i ' },
{ title: ' University of Hawai`i, Hilo ' },
{ title: ' University of Hawai`i, Manoa ' },
{ title: ' University of Hawai`i, West O`ahu ' },
{ title: ' University of Health Sciences College of Osteopathic Medicine ' },
{ title: ' University of Houston ' },
{ title: ' University of Houston, Clear Lake ' },
{ title: ' University of Houston, Downtown ' },
{ title: ' University of Houston, Victoria ' },
{ title: ' University of Idaho ' },
{ title: ' University of the Incarnate Word ' },
{ title: ' University of Indianapolis ' },
{ title: ' University of Illinois at Chicago ' },
{ title: ' University of Illinois at Springfield ' },
{ title: ' University of Illinois at Urbana-Champaign ' },
{ title: ' University of Iowa ' },
{ title: ' University of Kansas ' },
{ title: ' University of Kansas Medical Center ' },
{ title: ' University of Kentucky ' },
{ title: ' University of La Vernee ' },
{ title: ' University of Louisiana at Lafayette ' },
{ title: ' University of Louisiana at Monroe ' },
{ title: ' University of Louisville ' },
{ title: ' University of Maine ' },
{ title: ' University of Maine at Farmington ' },
{ title: ' University of Maine at Fort Kent ' },
{ title: ' University of Maine at Presque Isle ' },
{ title: ' University of Mary Hardin-Baylor ' },
{ title: ' University of Mary Washington ' },
{ title: ' University of Maryland Baltimore County ' },
{ title: ' University of Maryland at Baltimore ' },
{ title: ' University of Maryland at College Park ' },
{ title: ' University of Maryland Eastern Shore ' },
{ title: ' University of Maryland University College ' },
{ title: ' University of Massachusetts at Amherst ' },
{ title: ' University of Massachusetts at Boston ' },
{ title: ' University of Massachusetts at Dartmouth ' },
{ title: ' University of Massachusetts at Lowell ' },
{ title: ' University of Massachusetts Medical School ' },
{ title: ' University of Medicine and Dentistry of New Jersey ' },
{ title: ' University of Memphis ' },
{ title: ' University of Miami ' },
{ title: ' University of Michigan-Ann Arbor ' },
{ title: ' University of Michigan-Dearborn ' },
{ title: ' University of Michigan-Flint ' },
{ title: ' University of Minnesota-Crookston ' },
{ title: ' University of Minnesota-Duluth ' },
{ title: ' University of Minnesota-Morris ' },
{ title: ' University of Minnesota-Twin Cities ' },
{ title: ' University of Mississippi ' },
{ title: ' University of Missouri-Columbia ' },
{ title: ' University of Missouri-Kansas City ' },
{ title: ' University of Missouri-Saint Louis ' },
{ title: ' University of Montana, Missoula ' },
{ title: ' University of Montevallo ' },
{ title: ' University of Natural Medicine ' },
{ title: ' University of Nebraska, Kearney ' },
{ title: ' University of Nebraska, Lincoln ' },
{ title: ' University of Nebraska, Omaha ' },
{ title: ' University of Nevada, Las Vegas ' },
{ title: ' University of Nevada, Reno ' },
{ title: ' University of New England ' },
{ title: ' University of New Hampshire, Durham ' },
{ title: ' University of New Haven ' },
{ title: ' University of New Mexico ' },
{ title: ' University of New Orleans ' },
{ title: ' University of Newport ' },
{ title: ' University of North Alabama ' },
{ title: ' University of North Carolina at Asheville ' },
{ title: ' University of North Carolina at Chapel Hill ' },
{ title: ' University of North Carolina at Charlotte ' },
{ title: ' University of North Carolina at Greensboro ' },
{ title: ' University of North Carolina at Pembroke ' },
{ title: ' University of North Carolina at Wilmington ' },
{ title: ' University of North Dakota ' },
{ title: ' University of North Dakota--Lake Region ' },
{ title: ' University of North Florida ' },
{ title: ' University of North Texas ' },
{ title: ' University of Northern Colorado ' },
{ title: ' University of Northern Iowa ' },
{ title: ' University of Notre Dame ' },
{ title: ' University of Oklahoma ' },
{ title: ' University of Oregon ' },
{ title: ' University of Orlando ' },
{ title: ' University of Osteopathic Medicine and Health Science ' },
{ title: ' University of the Ozarks ' },
{ title: ' University of the Pacific ' },
{ title: ' University of Pennsylvania ' },
{ title: ' University of Phoenix ' },
{ title: ' University of Pittsburgh ' },
{ title: ' University of Pittsburgh at Bradford ' },
{ title: ' University of Pittsburgh at Greenburg ' },
{ title: ' University of Pittsburgh at Johnstown ' },
{ title: ' University of Portland ' },
{ title: ' University of Puerto Rico, Mayaguez ' },
{ title: ' University of Puerto Rico, Rio Piedras ' },
{ title: ' University of Puget Sound ' },
{ title: ' University of Redlands ' },
{ title: ' University of Rhode Island ' },
{ title: ' University of Richmond ' },
{ title: ' University of Rio Grande ' },
{ title: ' University of Rochester ' },
{ title: ' University of Saint Francis ' },
{ title: ' University of Saint Mary ' },
{ title: ' University of Saint Thomas, Houston ' },
{ title: ' University of Saint Thomas, Saint Paul ' },
{ title: ' University of San Diego ' },
{ title: ' University of San Francisco ' },
{ title: ' University of Sarasota ' },
{ title: ' University of Science and Arts of Oklahoma ' },
{ title: ' University of the Sciences in Philadelphia ' },
{ title: ' University of Scranton ' },
{ title: ' University of Sioux Falls ' },
{ title: ' University of the South ' },
{ title: ' University of South Alabama ' },
{ title: ' University of South Carolina ' },
{ title: ' University of South Carolina, Aiken ' },
{ title: ' University of South Carolina, Beaufort ' },
{ title: ' University of South Carolina, Spartanburg ' },
{ title: ' University of South Dakota ' },
{ title: ' University of South Florida ' },
{ title: ' University of Southern California ' },
{ title: ' University of Southern Indiana ' },
{ title: ' University of Southern Maine ' },
{ title: ' University of Southern Mississippi ' },
{ title: ' University of Tampa ' },
{ title: ' University of Tennessee, Chattanooga ' },
{ title: ' University of Tennessee Health Science Center ' },
{ title: ' University of Tennessee, Knoxville ' },
{ title: ' University of Tennessee, Martin ' },
{ title: ' University of Texas at Arlington ' },
{ title: ' University of Texas at Austin ' },
{ title: ' University of Texas at Brownsville ' },
{ title: ' University of Texas at Dallas ' },
{ title: ' University of Texas at El Paso ' },
{ title: ' University of Texas Health Science Center at Houston ' },
{ title: ' University of Texas Health Science Center at San Antonio ' },
{ title: ' University of Texas Health Center at Tyler ' },
{ title: ' University of Texas Medical Branch ' },
{ title: ' University of Texas-Pan American ' },
{ title: ' University of Texas of the Permian Basin ' },
{ title: ' University of Texas at San Antonio ' },
{ title: ' University of Texas at Tyler ' },
{ title: ' University of Texas Southwestern Medical Center ' },
{ title: ' University of the Southwest ' },
{ title: ' University of Toledo ' },
{ title: ' University of Tulsa ' },
{ title: ' University of Utah ' },
{ title: ' University of Vermont ' },
{ title: ' University of the Virgin Islands ' },
{ title: ' University of Virginia ' },
{ title: ' University of Washington ' },
{ title: ' University of West Alabama ' },
{ title: ' University of West Florida ' },
{ title: ' University of West Georgia ' },
{ title: ' University of Wisconsin-Green Bay ' },
{ title: ' University of Wisconsin-Eau Claire ' },
{ title: ' University of Wisconsin-La Crosse ' },
{ title: ' University of Wisconsin-Madison ' },
{ title: ' University of Wisconsin-Milwaukee ' },
{ title: ' University of Wisconsin-Oshkosh ' },
{ title: ' University of Wisconsin-Parkside ' },
{ title: ' University of Wisconsin-Platteville ' },
{ title: ' University of Wisconsin-Stevens Point ' },
{ title: ' University of Wisconsin-Stout ' },
{ title: ' University of Wisconsin-Superior ' },
{ title: ' University of Wisconsin-River Falls ' },
{ title: ' University of Wisconsin-Whitewater ' },
{ title: ' University of Wyoming ' },
{ title: ' Upper Iowa University ' },
{ title: ' Urbana University ' },
{ title: ' Ursinus College ' },
{ title: ' Ursuline College ' },
{ title: ' Utah State University ' },
{ title: ' Utah Valley State College ' },
{ title: ' Utica College ' },
{ title: ' Valdosta State University ' },
{ title: ' Valley City State University ' },
{ title: ' Valparaiso University ' },
{ title: ' Vanderbilt University ' },
{ title: ' Vanguard University ' },
{ title: ' Vassar College ' },
{ title: ' Vaughn College of Aeronautics ' },
{ title: ' Vennard College ' },
{ title: ' Vermont Technical College ' },
{ title: ' Villanova University ' },
{ title: ' Virginia Commonwealth University ' },
{ title: ' Virginia Intermont College ' },
{ title: ' Virginia International University ' },
{ title: ' Virginia Military Institute ' },
{ title: ' Virginia Polytechnic Institute and State University ' },
{ title: ' Virginia State University ' },
{ title: ' Virginia Union University ' },
{ title: ' Virginia University of Lynchburg ' },
{ title: ' Virginia Wesleyan College ' },
{ title: ' Viterbo College ' },
{ title: ' Voorhees College ' },
{ title: ' Wabash College ' },
{ title: ' Wagner College ' },
{ title: ' Wake Forest University ' },
{ title: ' Warner Pacific College ' },
{ title: ' Wartburg College ' },
{ title: ' Walden University ' },
{ title: ' Waldorf College ' },
{ title: ' Walla Walla University ' },
{ title: ' Walsh University ' },
{ title: ' Warren Wilson College ' },
{ title: ' Washburn University ' },
{ title: ' Washington & Jefferson College ' },
{ title: ' Washington & Lee University ' },
{ title: ' Washington Bible College / Capital Bible Seminary ' },
{ title: ' Washington College ' },
{ title: ' Washington State University ' },
{ title: ' Washington University in Saint Louis ' },
{ title: ' Watkins College of Art, Design and Film ' },
{ title: ' Wayland Baptist University ' },
{ title: ' Wayne State College ' },
{ title: ' Wayne State University ' },
{ title: ' Waynesburg College ' },
{ title: ' Webb Institute ' },
{ title: ' Weber State University ' },
{ title: ' Webster University ' },
{ title: ' Webster University North Florida ' },
{ title: ' Webster University Orlando ' },
{ title: ' Wellesley College ' },
{ title: ' Wells College ' },
{ title: ' Wentworth Institute of Technology ' },
{ title: ' Wesley College ' },
{ title: ' Wesleyan College ' },
{ title: ' Wesleyan University ' },
{ title: ' West Coast University ' },
{ title: ' West Chester University of Pennsylvania ' },
{ title: ' West Liberty State College ' },
{ title: ' West Texas A&M University ' },
{ title: ' West Virginia State University ' },
{ title: ' West Virginia University ' },
{ title: ' West Virginia University Parkersburg ' },
{ title: ' West Virginia Wesleyan College ' },
{ title: ' Western Baptist College ' },
{ title: ' Western Carolina University ' },
{ title: ' Western Connecticut State University ' },
{ title: ' Western Governors University ' },
{ title: ' Western Illinois University ' },
{ title: ' Western International University ' },
{ title: ' Western Kentucky University ' },
{ title: ' Western Maryland College ' },
{ title: ' Western Michigan University ' },
{ title: ' Western Montana College ' },
{ title: ' Western New England College ' },
{ title: ' Western New Mexico University ' },
{ title: ' Western Oregon University ' },
{ title: ' Western State College ' },
{ title: ' Western State University College of Law ' },
{ title: ' Western States Chiropractic College ' },
{ title: ' Western University of Health Sciences ' },
{ title: ' Western Washington University ' },
{ title: ' Westfield State College ' },
{ title: ' Westminster College, Fulton Missouri ' },
{ title: ' Westminster College, New Wilmington Pennsylvania ' },
{ title: ' Westminster College, Salt Lake City ' },
{ title: ' Westminster Theological Seminary ' },
{ title: ' Westminster Theological Seminary in California ' },
{ title: ' Westmont College ' },
{ title: ' Westwood College — California ' },
{ title: ' Westwood College — Colorado ' },
{ title: ' Westwood College — Georgia ' },
{ title: ' Westwood College — Illinois ' },
{ title: ' Westwood College — Texas ' },
{ title: ' Westwood College — Virginia ' },
{ title: ' Westwood College of Technology ' },
{ title: ' Wheaton College, Wheaton Illinois ' },
{ title: ' Wheaton College, Massachusetts ' },
{ title: ' Wheeling Jesuit University ' },
{ title: ' Wheelock College ' },
{ title: ' Whitman College ' },
{ title: ' Whittier College ' },
{ title: ' Whitworth University ' },
{ title: ' Wichita State University ' },
{ title: ' Widener University ' },
{ title: ' Wilberforce University ' },
{ title: ' Wilkes University ' },
{ title: ' Willamette University ' },
{ title: ' William Carey International University ' },
{ title: ' William Howard Taft University ' },
{ title: ' William Jessup University ' },
{ title: ' William Jewell College ' },
{ title: ' William Mitchell College of Law ' },
{ title: ' William Paterson University ' },
{ title: ' William Penn College ' },
{ title: ' William Woods University ' },
{ title: ' Williams Baptist College ' },
{ title: ' William Carey University ' },
{ title: ' Williams College ' },
{ title: ' Wilmington College, New Castle Delaware ' },
{ title: ' Wilmington College, Wilmington Ohio ' },
{ title: ' Wilson College ' },
{ title: ' Wingate University ' },
{ title: ' Winston-Salem State University ' },
{ title: ' Winona State University ' },
{ title: ' Winthrop University ' },
{ title: ' Wisconsin Lutheran College ' },
{ title: ' Wittenberg University ' },
{ title: ' Wofford College ' },
{ title: ' Woodbury University ' },
{ title: ' Woods Hole Oceanographic Institution ' },
{ title: ' Worcester Polytechnic Institute ' },
{ title: ' Worcester State College ' },
{ title: ' Wright Institute ' },
{ title: ' Wright State University ' },
{ title: ' Xavier University, Cincinnati, OH ' },
{ title: ' Xavier University of Louisiana ' },
{ title: ' Yale University ' },
{ title: ' Yeshiva University ' },
{ title: ' York College, York Nebraska ' },
{ title: ' York College of Pennsylvania ' },
{ title: ' Youngstown State University ' },
{ title: ' Zion Bible Institute ' },
];

export default colleges;